services:
  user-service:
    build:
      context: .
      dockerfile: ./cmd/user-service/Dockerfile
    container_name: user-service
    ports:
      - "50051:50051"

  auth-service:
    build:
      context: .
      dockerfile: ./cmd/auth-service/Dockerfile
    container_name: auth-service
    environment:              
      - USERSERVICEADDR=user-service:50051  
    ports:
      - "50052:50052"
    depends_on:
      - user-service

  gateway:
    build:
      context: .
      dockerfile: ./cmd/gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
